<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-CT7IBV5D" name="com.qa.RESTfulAPI.TestCases.GetRESTful_WebService_UsingBasicAuthentication" tests="2" failures="1" timestamp="24 Oct 2018 16:26:06 GMT" time="5.294" errors="0">
  <testcase name="getRESTful_Webservice_basicAuthentication_TC01" time="3.485" classname="com.qa.RESTfulAPI.TestCases.GetRESTful_WebService_UsingBasicAuthentication"/>
  <testcase name="getRESTful_Webservice_basicAuthentication_TC02" time="1.809" classname="com.qa.RESTfulAPI.TestCases.GetRESTful_WebService_UsingBasicAuthentication">
    <failure type="java.lang.AssertionError" message="Authentication Error; Wrong Username and Password expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Authentication Error; Wrong Username and Password expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.qa.RESTfulAPI.TestCases.GetRESTful_WebService_UsingBasicAuthentication.getRESTful_Webservice_basicAuthentication_TC02(GetRESTful_WebService_UsingBasicAuthentication.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getRESTful_Webservice_basicAuthentication_TC02 -->
</testsuite> <!-- com.qa.RESTfulAPI.TestCases.GetRESTful_WebService_UsingBasicAuthentication -->
